### ISSUE TITLE
consider removing issues from this repository

### ISSUE THREAD

**Issue by aarondandy** [adamralph/bau-nuget#1]
Consider using the primary Bau repository for issues, etc...

**Comment by aarondandy** [comment]
If you like milestones that may be a reason to keep issues enabled on the project.

**Comment by adamralph** [comment]
At the moment I'm favouring keeping them.

**Comment by adamralph** [comment]
Let's keep them for now. We seem to be making good use of them already and I like that they are not mixed in with the main Bau tasks. We can always consider again later after the repo has lived for a while.
