### ISSUE TITLE
CI build

### ISSUE THREAD

**Issue by adamralph** [adamralph/bau-nuget#18]
Either http://teamcity.codebetter.com/ or https://ci.appveyor.com/. We could also try for a Mono build on https://travis-ci.org/ but I'm not sure how well NuGet.exe plays on *nix these days.
- [x] appveyor
- [x] travisci

**Comment by aarondandy** [comment]
I have only used TC local, not hosted so whatever you think is easier. I definitely want this build on windows because of the tests, etc. I would consider travis later after a few releases as I don't have any OSX or linux machines available at the moment to test with.

**Comment by adamralph** [comment]
We _should_ be able to build on Travis right away if NuGet.exe works on *nix.

**Comment by aarondandy** [comment]
Appveyor is working fine. Should add the badge to the readme. Should also add a readme.

**Comment by aarondandy** [comment]
Read me added in #27
