### ISSUE TITLE
ambiguous reference in dog food script :dog:

### ISSUE THREAD

**Issue by aarondandy** [adamralph/bau-nuget#20]
The dog.csx script has an ambiguous reference:

ERROR: dog.csx(3,57): error CS0104: 'Verbosity' is an ambiguous reference between 'BauMSBuild.Verbosity' and 'BauNuGet.Verbosity'

Broken by: 48745e6dd6c4c389f91d9a3c2348b9c91284982c

**Comment by adamralph** [comment]
Hmmm... painful. Wondering what we can do about this. Perhaps we should name the enum `NuGetVerbosity`?

**Comment by adamralph** [comment]
And likewise, I should change the MSBuild one to `MSBuildVerbosity` over in that repo.

**Comment by adamralph** [comment]
Or actually, why not leave people to qualify the type with the namespace? That's what namespaces are for I guess!

**Comment by aarondandy** [comment]
- `.WithVerbosity(NuGetVerbosity.Detailed)`
- `.WithVerbosity(BauNuGet.Verbosity.Detailed)`
- `.WithVerbosityDetailed()`
- `.WithVerbosity("detailed")`

**Comment by aarondandy** [comment]
I still think this is a bug as it will be encountered by anybody who wants to mess with verbosity, which honestly is nobody ever probably.

**Comment by adamralph** [comment]
I don't think it's a bug since things are behaving as designed.

I'm fixing the dogfooding scripts now. I'll spin off another issue where we can discuss a potentially nicer API.

**Comment by aarondandy** [comment]
While working this issue consider #22
