### ISSUE TITLE
Better verbosity API

### ISSUE THREAD

**Issue by adamralph** [adamralph/bau-nuget#21]
Spun off from #20.

Currently, due to a clash with `BauMSBuild.Verbosity`, it's necessary to fully qualify the type, e.g.

``` C#
.WithVerbosity(BauNuGet.Verbosity.Detailed)
```

Suggestions:

``` C#
.WithVerbosity(NuGetVerbosity.Detailed)
.WithVerbosity("detailed")
```

**Comment by aarondandy** [comment]
Using a string is a bit poopy and made more sense back when the code was using reflection to call commands on NuGet.exe . So using the enum it is down to 2 choices:
- `BauNuGet.Verbosity.Detailed`
- `NuGetVerbosity.Detailed`

I think I would rather type `NuGetVerbosity.Detailed`

**Comment by adamralph** [comment]
I agree.
