### ISSUE TITLE
fix build for scriptcs 0.13

### ISSUE THREAD

**Issue by adamralph** [adamralph/bau-nuget#39]
Fails due to https://github.com/scriptcs/scriptcs/issues/912, which can be worked around by running `scriptcs -install` separately before `scriptcs ./baufile.csx`.

Also fails because `baufile.csx` is looking in `packages/` instead of `scriptcs_packages`.

*nix build needs to change to download a new blob. The one it is using is based on scriptcs 0.10.

**Comment by aarondandy** [comment]
I am able to run the script and install in one go using the `-script` parameter: `scriptcs -script baufile.csx -I`

**Comment by adamralph** [comment]
That's another way to work around it. Note that it is not the `-script` parameter that is helping you there, it's the `-I` (install) parameter.

**Comment by adamralph** [comment]
It is also a better way, so I've updated the workaround in the issue desc to use it :wink:

**Comment by adamralph** [comment]
Hmmm... I take it back. `scriptcs -script baufile.csx -I` doesn't fix it, and I just looked through the code and confirmed that there is no way it _could_ fix it. The place where I tried it out initially was working successfully for other reasons.

I'm fairly convinced the only workaround is run a separate `scriptcs -install` first.

**Comment by aarondandy** [comment]
Going to make an attempt at this, continuing your work.
