### ISSUE TITLE
fix appveyor build status reporting on PRs

### ISSUE THREAD

**Issue by adamralph** [adamralph/bau-nuget#40]
Doesn't seem to be working, e.g. 

![image](https://cloud.githubusercontent.com/assets/677704/6040325/d0bf233a-ac70-11e4-9b85-f208bb5037e4.png)

![image](https://cloud.githubusercontent.com/assets/677704/6040331/e09b50b2-ac70-11e4-9b71-98c32932553b.png)

**Comment by adamralph** [comment]
Raised http://help.appveyor.com/discussions/problems/1499-build-status-not-showing-on-github-pr

**Comment by aarondandy** [comment]
Wasn't this due to GutHub only showing the results of one build at a time? We have both Travis and AppVeyor on this. Has that been fixed/enhanced by GitHub yet?

**Comment by adamralph** [comment]
The multiple status feature has indeed been added by GitHub and it works perfectly on all other projects I'm working on which have multiple builds. Why it isn't working here is a mystery.

**Comment by aarondandy** [comment]
I'm not sure if you are fixing it or not but I noticed that the app-veyor started running.
![image](https://cloud.githubusercontent.com/assets/404933/6094076/39361bd6-aed7-11e4-9063-57942c3f133a.png)

**Comment by aarondandy** [comment]
PR #41 shows this working again, not sure why though.

**Comment by adamralph** [comment]
Oh, well that's great. Perhaps the issue has just 'fixed itself' then. I'll double check everything and close this if so.

**Comment by adamralph** [comment]
It's working for both our current PR's so I guess it has magically been fixed.
