### ISSUE TITLE
Extract task execution logic from NuGetBauTaskBase and children.

### ISSUE THREAD

**Issue by aarondandy** [adamralph/bau-nuget#5]
Removing the Core and CLI implementation code from the Tasks will improve organization and allow more more flexibility with respect to other refactoring issues.

**Comment by adamralph** [comment]
Is this a pure refactoring or is there any feature change? We have a refactoring label for the latter now.

**Comment by aarondandy** [comment]
Created the new label using values from bau-build/bau and applied it. This is 100% a refactoring item.

**Comment by adamralph** [comment]
:+1:

**Comment by aarondandy** [comment]
Looks much cleaner to me. :shipit:

**Comment by adamralph** [comment]
I don't think there's any reason to include refactorings in milestones. I think that should be restricted to features and bugs only, i.e. anything that you would put in release notes.
