### ISSUE TITLE
Initial code review of the project

### ISSUE THREAD

**Issue by aarondandy** [adamralph/bau-nuget#7]
Review and possibly Ralphactor the Bau.NuGet code.

**Comment by adamralph** [comment]
LOL... with pleasure! :smile: I'm travelling for most of tomorrow so that will be a good opportunity. I'll make sure I fetch latest before boarding the plane :smiley:

**Comment by adamralph** [comment]
@aarondandy I've completed my initial review and raised 3 issues, #8, #9 and #10.

**Comment by blairconrad** [comment]
Sorry to intrude, but "Ralphactor" is gold. Gold, @aarondandy! :moneybag:

**Comment by adamralph** [comment]
My work team mates deserve the credit :stuck_out_tongue_closed_eyes:

**Comment by blairconrad** [comment]
Please, pass along my admiration.

**Comment by adamralph** [comment]
Done :wink:
